version:"3.7" # version del docker-compose(?)
services: 
  app:
    build:
      args:
        user: laravel-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine 
    container_name: nginx
    ports:
      - 8000:80 
    volumes:
      - ./:/var/www/html 
      - ./docker-compose/nginx:/etc/nginx/conf.d/ 
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped 
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    networks:
    - laravel 

networks: # declaracion de la red
  laravel: