version: "3.3"
services:
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    networks:
    - laravel 

  nginx:
    image: nginx:alpine 
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80 
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/ 
    networks:
      - laravel

  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: laravel
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
